version: "2"
services:
  
  admin:
    build: ./admin
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - my-datavolume:/var/lib/mysql
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "admin.py"]
    networks:
      testing_net:
        ipv4_address: 172.11.1.2

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - my-datavolume:/var/run/mysql
    networks:
      testing_net:
        ipv4_address: 172.11.1.1

  server:
    build: ./server
    links:
      - db
    ports:
      - "8000:5000"
    networks:
      testing_net:
        ipv4_address: 172.11.1.3
    depends_on:
      - admin
    volumes:
      - my-datavolume:/var/run/mysql


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/16

volumes:
  my-datavolume:
